apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-deployment
  labels:
    app: ims
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ims
  template:
    metadata:
      labels:
        app: ims
    spec:
      containers:
      - name: ims
        image: ims-image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: db_root_password
            valueFrom:
              secretKeyRef:
                name: ims-secrets
                key: db_root_password
          - name: db_name
            value: ims
          - name: es_index
            value: search-ims-prod

---
apiVersion: v1
kind: Service
metadata:
  name: ims-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: ims
  type: LoadBalancer