---
apiVersion: v1
kind: Secret
metadata:
  name: ims-secrets
type: Opaque
data:
  db_root_password: cm1ZdGU3TUljbQ==
  elastic_cloud_id: YmFzZTY0Y2xvdWRpZA==
  elastic_user_password: YmFzZTY0cGFzc3dvcmQ=